# Generated by Django 6.0 on 2025-12-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prospect",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="prospect",
            name="last_name",
            field=models.CharField(default="b", max_length=255),
            preserve_default=False,
        ),
    ]
