# Generated by Django 6.0 on 2025-12-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_rename_name_prospect_first_name_prospect_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="scheduled_at",
        ),
    ]
