{
 "title": "Server Stats",
 "panels": [
  {
   "title": "CPU Usage (Now)",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage (Over Time)",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Network Receive Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "histogram",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "node_transactions_latency_ms" }
   ]
  }
 ]
}