services:
  web:
    restart: unless-stopped
    image: ${ECR_URL}/mp-web:${IMAGE_TAG}
    ports:
      - 80:80
    volumes:
      - django_static:/app/django_static
      - media:/app/media
    depends_on:
      - api
    networks:
      - prowess_network
    env_file:
      - .fe.env

  api:
    restart: unless-stopped
    image: ${ECR_URL}/mp-api:${IMAGE_TAG}
    volumes:
      - django_static:/app/django_static
      - media:/app/media
    networks:
      - prowess_network
    environment:
      POSTGRES_DB: prowessdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_HOST: ${POSTGRES_HOST} 
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: "app-alb-1194072423.ap-northeast-1.elb.amazonaws.com,mathprowess.com"

  prometheus:
    image: ${ECR_URL}/mp-prom:${IMAGE_TAG} 
    ports:
      - "9090:9090"
    networks:
      - prowess_network

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - prowess_network

  node_exporter:
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - prowess_network

volumes:
  django_static:
  media:
  grafana_data:

networks:
  prowess_network:
